apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shopping-cart
  title: 'Shopping Cart'
spec:
  type: website
  lifecycle: production
  owner: guests

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ecommerce
  title: 'Ecommerce'
spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-service
  # The title will override the name above. In case title is missing 
  # The component name is auth-service in Web Interface
  title: 'Authentication Service'
  description: authentication service
  tags:
    - javascript
  links:
    - url: https://google.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: guests

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  title: 'Pet Store'
  description: The Petstore API
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
  
